'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import BrandLogo from '../brand-logo';
import type {Promoter} from '../organizer/workspace/suite-promote';
import {money,date} from '../organizer/workspace/suite-shared';
export default function PromoterPortal(){
 const token=useRef(''),[report,setReport]=useState<Promoter|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!token.current)token.current=new URLSearchParams(location.hash.slice(1)).get('token')??'';history.replaceState(null,'',location.pathname);const c=new AbortController();void fetch('/api/promoter',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:token.current}),signal:c.signal}).then(async r=>{const d=await r.json() as Promoter&{error?:string};if(!r.ok)throw new Error(d.error);setReport(d);setError('');}).catch((e:Error)=>{if(!c.signal.aborted)setError(e.message||'This report could not be loaded.');});return()=>c.abort();},[retry]);
 return <main className="organizer-suite"><header className="suite-topbar"><Link href="/" className="night-brand-link"><BrandLogo/></Link><span>Private promoter report</span></header><div className="suite-content" style={{margin:'auto',maxWidth:900}}>{error?<p role="alert">{error}</p>:!report?<p role="status">Loading your report…</p>:null}{report?<section className="suite-section"><header><div><p className="suite-eyebrow">{report.label}</p><h1>{report.eventTitle}</h1></div><button onClick={()=>setRetry(v=>v+1)}>Refresh report</button></header><label>Your ticket link<input readOnly value={`https://tickets.becoreops.com/event/${report.eventSlug}?ref=${encodeURIComponent(report.code)}`} onFocus={e=>e.target.select()}/></label><div className="suite-stats">{[['Orders',report.orders],['Commission earned',money(report.earnedMinor)],['Payments recorded',money(report.paidMinor)],['Balance',money(report.balanceMinor)]].map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</div><p>Current rate: {report.commissionBps/100}% of discounted ticket value, excluding booking fees. Each order keeps its rate from checkout. Refunds reduce commission.</p><h3>Payment records</h3>{report.payments.map(p=><article key={p.id}><b>{money(p.amountMinor)}</b><p>{p.reference} · {date(p.paidAt)}</p></article>)}{!report.payments.length?<p>No payment records yet. Your host records completed payments here.</p>:null}</section>:error?<button onClick={()=>setRetry(v=>v+1)}>Try again</button>:null}</div></main>;
}
