import { test, expect } from './analytics-fixture';
import AxeBuilder from '@axe-core/playwright';

test('boxed quantity preserves purchase limits, totals and tier changes', async ({ page, baseURL }) => {
  test.skip(!test.info().config.configFile?.endsWith('playwright.seev.config.ts'), 'Requires the isolated checkout fixture.');
  test.skip(!baseURL || !['localhost', '127.0.0.1'].includes(new URL(baseURL).hostname), 'Synthetic local inventory only.');
  await page.route('**/api/config/booking-fee?*', route => route.fulfill({ json: { percentage: 5 } }));
  await page.route('**/api/payments/initialize', route => route.abort());
  await page.goto('/checkout/after-dark-osu');
  const quantity = page.getByRole('combobox', { name: 'General admission quantity' });
  await expect(quantity).toBeEnabled();
  await expect(quantity).toHaveValue('1');
  await expect(quantity.locator('option')).toHaveText(['1', '2', '3', '4', '5', '6']);
  const box = (await quantity.boundingBox())!;
  expect(box.width).toBeGreaterThanOrEqual(44);
  expect(box.height).toBeGreaterThanOrEqual(44);
  await quantity.focus();
  await expect(quantity).toBeFocused();
  expect(await quantity.evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe('none');
  await quantity.selectOption('3');
  await expect(page.locator('.summary-lines')).toContainText('3 × General admission');
  await expect(page.locator('.summary-lines')).toContainText('GH₵360');
  await expect(page.locator('.summary-lines')).toContainText('GH₵18');
  await expect(page.locator('.summary-lines > strong')).toHaveText('Total GH₵378');
  await page.getByRole('radio', { name: /Table for 5/ }).click();
  const tableQuantity = page.getByRole('combobox', { name: 'Table for 5 quantity' });
  await expect(tableQuantity).toHaveValue('1');
  await expect(tableQuantity.locator('option')).toHaveText(['1', '2']);
  await tableQuantity.selectOption('2');
  await expect(page.locator('.summary-lines')).toContainText('Admissions included 10');
  await expect(page.locator('.summary-lines > strong')).toHaveText('Total GH₵1,785');
  await page.getByRole('radio', { name: /General admission/ }).click();
  await expect(quantity).toHaveValue('1');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await quantity.evaluate(element => getComputedStyle(element).boxShadow)).toBe('none');
  const accessibility = await new AxeBuilder({ page }).include('.ticket-tier-list').analyze();
  expect(accessibility.violations).toEqual([]);
  await page.locator('.checkout-step').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('boxed-ticket-quantity.png') });
});
