import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("USDC stays explicit, preserves details and safely retries without changing the payment attempt", async ({ page }) => {
  test.skip(!test.info().config.configFile?.endsWith("playwright.seev-crypto.config.ts"), "Requires the isolated crypto UI configuration.");
  const requests: { key: string; body: Record<string, unknown> }[] = [];
  let releasePayment!: () => void;
  let stopped = new Promise<void>(resolve => { releasePayment = resolve; });
  await page.route("**/api/payments/initialize", async route => {
    requests.push({ key: route.request().headers()["idempotency-key"], body: route.request().postDataJSON() });
    await stopped;
    await route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Test payment stopped before contacting SeevPlus." }) });
  });
  await page.goto("/checkout/after-dark-osu");
  await page.getByLabel("Full name").fill("Crypto Test Buyer");
  await page.getByLabel("Phone number").fill("0240000000");
  await page.getByLabel("Email address").fill("crypto-test@example.com");
  await page.getByRole("radio", { name: /Mobile Money/ }).check();
  const momoNetworks = page.getByRole("list", { name: "Available mobile money networks" });
  await expect(momoNetworks).toContainText("MTN MoMo");
  await expect(momoNetworks).toContainText("Telecel Cash");
  await expect(momoNetworks).toContainText("AT Money");
  await page.getByRole("radio", { name: /Cards Visa/ }).check();
  await expect(page.getByRole("img", { name: "Accepted cards: Visa and Mastercard" })).toBeVisible();
  await expect(momoNetworks).toHaveCount(0);
  await page.getByRole("radio", { name: /Crypto USDC/ }).check();
  await expect(page.getByRole("group", { name: "Pay through" })).toHaveCount(0);
  await expect(page.getByRole("radiogroup", { name: "Choose mobile money service" })).toHaveCount(0);
  await expect(page.getByText(/Use only the asset and network shown there/)).toBeVisible();
  const pay = page.getByRole("button", { name: /Continue to USDC payment/ });
  await expect(pay).toContainText("GH₵");
  await pay.click();
  await expect(page.locator("#checkout-payment-message")).toHaveText("Tick the ticket terms, refund rules and privacy checkbox to continue.");
  expect(requests).toHaveLength(0);
  await page.getByRole("checkbox", { name: /I accept the ticket terms/ }).check();
  await pay.click();
  await expect.poll(() => requests.length).toBe(1);
  await expect(page.getByRole("radio", { name: /Mobile Money/ })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Making it official…" })).toBeDisabled();
  releasePayment();
  await expect(page.locator("#checkout-payment-message")).toHaveText("Test payment stopped before contacting SeevPlus.");
  expect(requests[0].body).toMatchObject({ paymentProvider: "seevplus", paymentMethod: "crypto", acceptedPolicies: true });
  expect(requests[0].body.network).toBeUndefined();
  expect(requests[0].key).toBeTruthy();
  stopped = Promise.resolve();
  await pay.click();
  await expect.poll(() => requests.length).toBe(2);
  await expect(page.locator("#checkout-payment-message")).toHaveText("Test payment stopped before contacting SeevPlus.");
  expect(requests[1]).toEqual(requests[0]);
  await expect(page.getByLabel("Full name")).toHaveValue("Crypto Test Buyer");
  await expect(page.getByLabel("Email address")).toHaveValue("crypto-test@example.com");
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  expect(await page.content()).not.toContain("ui-test-only");
  expect((await new AxeBuilder({ page }).include(".payment-methods").analyze()).violations).toEqual([]);
  await page.screenshot({ path: `test-results/seevplus-crypto-${test.info().project.name}.png`, fullPage: true });
  await page.getByRole("radio", { name: /Cards Visa/ }).check();
  await expect(page.getByText("Paystack handles the money. We handle the night.")).toBeVisible();
  await expect(page.getByLabel("Full name")).toHaveValue("Crypto Test Buyer");
});
