import type { CuratedEvent } from "../app/events";

export const ticketSelectionEvent: CuratedEvent = {
  slug: "test-event",
  title: "Test Event",
  shortDate: "30 DEC",
  fullDate: "Wednesday, 30 December 2026",
  day: "Wednesday",
  time: "8:00 PM — 2:00 AM",
  startsAt: "2026-12-30T20:00:00.000Z",
  endsAt: "2026-12-31T02:00:00.000Z",
  venue: "Test Venue",
  venueMapUrl: "https://maps.google.com/?q=Test+Venue",
  area: "Accra",
  vibe: "Late night",
  price: 120,
  priceFromMinor: 12_000,
  bookingFeeBasisPoints: 750,
  capacity: 200,
  ageRestriction: "18+",
  lineup: "Test DJ",
  eventState: "on_sale",
  isTestEvent: false,
  rescheduledFrom: null,
  salesOpenAt: null,
  salesCloseAt: "2026-12-30T20:00:00.000Z",
  image: "https://example.com/test.jpg",
  note: "A sufficiently detailed customer-facing event note for testing.",
  quip: "Small room. Big decisions.",
  sequence: "01",
  ticketTiers: [
    { id: "general", recordId: "test:general", name: "General admission", description: "One admission", priceMinor: 12_000, admissionsPerUnit: 1, maxUnitsPerOrder: 10, capacityAdmissions: 100, remainingAdmissions: 100, status: "available", roomBadge: null },
    { id: "vip", recordId: "test:vip", name: "VIP", description: "Priority admission", priceMinor: 25_000, admissionsPerUnit: 1, maxUnitsPerOrder: 10, capacityAdmissions: 50, remainingAdmissions: 50, status: "available", roomBadge: "VIP" },
    { id: "table-for-5", recordId: "test:table", name: "Table for 5", description: "Five admissions", priceMinor: 180_000, admissionsPerUnit: 5, maxUnitsPerOrder: 2, capacityAdmissions: 50, remainingAdmissions: 50, status: "available", roomBadge: null },
  ],
};
