import {env} from 'cloudflare:test';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {submitHostApplication,confirmHostApplication,inspectHostApplication,reviewHostApplication,processPendingHostAccess,validateHostInput} from '../lib/host-applications';
import {retryFailedDeliveries} from '../lib/email-delivery';
import {adminCookieHeader,createStaffSession} from '../lib/admin-session';
import {GET,PATCH} from '../app/api/admin/host-applications/route';
import {POST} from '../app/api/host-applications/route';
const origin='https://tickets.becoreops.com';
const input=()=>({brandName:'Good nights',contactName:'Test host',email:`${crypto.randomUUID()}@example.com`,phone:'+233240000000',socialUrl:'https://example.com/host',about:'Day parties',acceptedPolicies:true});
async function application(){const data=input();await submitHostApplication(env.DB,data);const row=await env.DB.prepare(`SELECT a.id,d.payload_json AS payload FROM host_applications a JOIN delivery_events d ON d.recovery_grant_id=a.verification_hash WHERE a.email=?`).bind(data.email).first<{id:string;payload:string}>();const token=JSON.parse(row!.payload).text.match(/#token=([\w-]{43})/)[1];return {data,id:row!.id,token};}
async function ready(){const a=await application();await confirmHostApplication(env.DB,a.token);return a;}
async function account(role='owner'){const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO staff_accounts(id,normalized_email,display_name,role,password_hash,password_salt,password_iterations,must_change_password,status,password_changed_at,created_at,created_by,updated_at) VALUES(?,?,'Tester',?,'unused','unused',600000,0,'active',?,?, 'test',?)`).bind(id,`${id}@example.com`,role,now,now,now).run();return {id,cookie:adminCookieHeader(await createStaffSession(env.DB,{id}))};}
function request(path:string,body?:object,cookie?:string,method='POST'){return new Request(origin+path,{method:body?method:'GET',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});}
beforeEach(()=>vi.spyOn(globalThis,'fetch').mockImplementation(async()=>Response.json({id:crypto.randomUUID()})));
afterEach(()=>vi.restoreAllMocks());
describe('host onboarding without an event',()=>{
 it('persists the application and private confirmation outbox atomically without an account',async()=>{const a=await application();expect(await inspectHostApplication(env.DB,a.token)).toMatchObject({brandName:a.data.brandName});expect(await env.DB.prepare('SELECT 1 FROM staff_accounts WHERE normalized_email=?').bind(a.data.email).first()).toBeNull();expect(await env.DB.prepare('SELECT 1 FROM party_submissions WHERE contact_email=?').bind(a.data.email).first()).toBeNull();expect(await env.DB.prepare('SELECT policy_versions FROM host_applications WHERE id=?').bind(a.id).first()).toHaveProperty('policy_versions');});
 it('deduplicates retries and will not replace verified data',async()=>{const a=await application();await submitHostApplication(env.DB,{...a.data,brandName:'Changed'});expect(await inspectHostApplication(env.DB,a.token)).toMatchObject({brandName:a.data.brandName});await confirmHostApplication(env.DB,a.token);await submitHostApplication(env.DB,{...a.data,brandName:'Changed'});expect(await env.DB.prepare('SELECT brand_name,status FROM host_applications WHERE id=?').bind(a.id).first()).toEqual({brand_name:a.data.brandName,status:'pending'});});
 it('confirms once, rejects replay and expires links',async()=>{const a=await application();const r=await Promise.allSettled([confirmHostApplication(env.DB,a.token),confirmHostApplication(env.DB,a.token)]);expect(r.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(await inspectHostApplication(env.DB,a.token)).toBeNull();const b=await application();await env.DB.prepare("UPDATE host_applications SET verification_expires_at='2000-01-01' WHERE id=?").bind(b.id).run();await expect(confirmHostApplication(env.DB,b.token)).rejects.toThrow();});
 it('rotates stale unconfirmed links and suppresses old verification deliveries',async()=>{const a=await application();await env.DB.prepare("UPDATE host_applications SET updated_at='2000-01-01' WHERE id=?").bind(a.id).run();await submitHostApplication(env.DB,a.data);expect(await inspectHostApplication(env.DB,a.token)).toBeNull();await retryFailedDeliveries(env,100,'host_applications');expect(vi.mocked(fetch).mock.calls.filter(([,init])=>String(init?.body).includes(a.data.email))).toHaveLength(1);});
 it('approves an email-confirmed host, creates a verified profile and only their own empty account',async()=>{const a=await ready();await reviewHostApplication(env.DB,a.id,'approve','test','Checked social page');await processPendingHostAccess(env.DB);const row=await env.DB.prepare('SELECT account_id,host_id,access_pending,status FROM host_applications WHERE id=?').bind(a.id).first<{account_id:string;host_id:string;access_pending:number;status:string}>();expect(row).toMatchObject({access_pending:0,status:'approved'});expect(await env.DB.prepare('SELECT role,status FROM staff_accounts WHERE id=?').bind(row!.account_id).first()).toEqual({role:'organizer',status:'active'});expect(await env.DB.prepare('SELECT 1 FROM staff_event_assignments WHERE account_id=?').bind(row!.account_id).first()).toBeNull();expect(await env.DB.prepare('SELECT verification_status FROM hosts WHERE id=?').bind(row!.host_id).first()).toEqual({verification_status:'verified'});expect(await env.DB.prepare('SELECT 1 FROM organizer_invitations WHERE account_id=?').bind(row!.account_id).first()).not.toBeNull();});
 it('does not approve unconfirmed applicants or alter privileged accounts',async()=>{const a=await application();await expect(reviewHostApplication(env.DB,a.id,'approve','test','')).rejects.toThrow('Only email');await confirmHostApplication(env.DB,a.token);const owner=await account();await env.DB.prepare('UPDATE staff_accounts SET normalized_email=? WHERE id=?').bind(a.data.email,owner.id).run();await expect(reviewHostApplication(env.DB,a.id,'approve','test','')).rejects.toThrow('another staff role');expect(await env.DB.prepare('SELECT status FROM host_applications WHERE id=?').bind(a.id).first()).toEqual({status:'pending'});});
 it('concurrent reviews commit only one decision and one profile',async()=>{const a=await ready();const r=await Promise.allSettled([reviewHostApplication(env.DB,a.id,'approve','test',''),reviewHostApplication(env.DB,a.id,'reject','test','')]);expect(r.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await env.DB.prepare("SELECT COUNT(*) AS count FROM operational_audit_events WHERE target_type='host_application' AND target_id=?").bind(a.id).first<{count:number}>())?.count).toBe(1);});
 it('declines without creating an account and queues an outcome email',async()=>{const a=await ready();await reviewHostApplication(env.DB,a.id,'reject','test','Internal note');expect(await env.DB.prepare('SELECT 1 FROM staff_accounts WHERE normalized_email=?').bind(a.data.email).first()).toBeNull();const delivery=await env.DB.prepare("SELECT payload_json FROM delivery_events WHERE recipient=? AND kind='host_application_decision'").bind(a.data.email).first<{payload_json:string}>();expect(delivery!.payload_json).not.toContain('Internal note');expect(delivery!.payload_json).toContain('couldn’t approve');});
 it('links an owner-selected existing profile without duplicating it',async()=>{const a=await ready();await reviewHostApplication(env.DB,a.id,'approve','test','','host:kofi-bills');expect(await env.DB.prepare('SELECT host_id FROM host_applications WHERE id=?').bind(a.id).first()).toEqual({host_id:'host:kofi-bills'});});
 it('keeps data when email provider fails',async()=>{vi.spyOn(env.PUBLIC_WRITE_RATE_LIMITER,'limit').mockResolvedValue({success:true});vi.mocked(fetch).mockImplementation(async(url)=>{if(String(url).includes('api.resend.com'))throw new Error('provider unavailable');return Response.json({id:crypto.randomUUID()});});const data=input();const r=await POST(request('/api/host-applications',data));expect(r.status).toBe(202);expect(await env.DB.prepare('SELECT status FROM host_applications WHERE email=?').bind(data.email).first()).toEqual({status:'awaiting_email'});expect(await env.DB.prepare('SELECT next_attempt_at FROM delivery_events WHERE recipient=?').bind(data.email).first()).toHaveProperty('next_attempt_at');});
 it('requires owner access, enforces origin, and shows confirmed applications in the dashboard queue',async()=>{expect((await GET(request('/api/admin/host-applications'))).status).toBe(403);const host=await account('organizer');expect((await GET(request('/api/admin/host-applications',undefined,host.cookie))).status).toBe(403);const owner=await account(),a=await ready();const r=await GET(request('/api/admin/host-applications',undefined,owner.cookie));expect(r.status).toBe(200);expect((await r.json() as {items:{id:string}[]}).items.some(x=>x.id===a.id)).toBe(true);const bad=new Request(origin+'/api/admin/host-applications',{method:'PATCH',headers:{origin:'https://attacker.example',cookie:owner.cookie},body:JSON.stringify({id:a.id,action:'approve'})});expect((await PATCH(bad)).status).toBe(403);});
 it('validates consent, contact data and unsafe links',()=>{for(const data of [{...input(),acceptedPolicies:false},{...input(),email:'invalid'},{...input(),socialUrl:'javascript:alert(1)'},{...input(),phone:'hello'}])expect(()=>validateHostInput(data)).toThrow();});
});
