'use client';
import {useCallback,useEffect,useState} from 'react';
import {ActionButton} from './action';
import {operationsFetch} from '../lib/operations-client';
import {announcementTemplates,type AnnouncementTemplate} from '../lib/announcement-template';
import {marketingAudiences,type MarketingAudience} from '../lib/marketing-audience';
type Campaign={id:string;subject:string;status:string;scheduledAt:string;recipientCount:number;error:string|null;metrics:Record<string,number>;metricsAt:string|null};
type Summary={configured:boolean;subscribed:number;synced:number;limit:number;state:{status:string;contactCount:number;reservedCount:number;checkedAt:string|null;error:string|null};campaigns:Campaign[];event:{title:string}};
const statusLabels:Record<string,string>={queued:'Scheduled / queued',preparing:'Preparing emails',sending:'Checking delivery',sent:'Handed to Resend',review:'Needs owner review',cancelled:'Cancelled'};
export default function AnnouncementComposer({eventSlug}:{eventSlug:string}){
 const [data,setData]=useState<Summary|null>(null),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[template,setTemplate]=useState<AnnouncementTemplate>('update'),[audience,setAudience]=useState<MarketingAudience>('all'),[scheduledAt,setScheduledAt]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState<{html:string;recipients:number;id:string}|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await operationsFetch(`/api/admin/campaigns?eventSlug=${encodeURIComponent(eventSlug)}`,{signal,cache:'no-store'});const result=await r.json() as Summary & {error?:string};if(signal?.aborted)return;if(!r.ok)throw new Error(result.error);setData(result);}catch(error){if(!signal?.aborted)setMessage(error instanceof Error?error.message:'Couldn’t load announcements.');}},[eventSlug]);
 useEffect(()=>{const controller=new AbortController();const initial=setTimeout(()=>void load(controller.signal),0);const timer=setInterval(()=>{if(!document.hidden)void load(controller.signal);},15000);return()=>{controller.abort();clearTimeout(initial);clearInterval(timer);};},[load]);
 async function act(action:'preview'|'send'|'cancel',id?:string){
  if(busy)return;setBusy(true);setMessage('');
  try{
   const response=await operationsFetch('/api/admin/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventSlug,action,id:id??preview?.id,subject,body,template,audience,scheduledAt:scheduledAt?new Date(`${scheduledAt}:00Z`).toISOString():null,recipients:preview?.recipients})});
   const result=await response.json() as {error?:string;html:string;recipients:number};if(!response.ok)throw new Error(result.error??'The announcement could not be saved.');
   if(action==='preview')setPreview({html:result.html,recipients:result.recipients,id:crypto.randomUUID()});
   else if(action==='cancel'){setMessage('Announcement cancelled.');await load();}
   else {setMessage(scheduledAt?'Announcement scheduled. Check its delivery status below.':'Announcement queued. Check its delivery status below.');setPreview(null);setSubject('');setBody('');setScheduledAt('');await load();}
  }catch(error){setMessage(error instanceof Error?error.message:'Connection lost. Your message is still here.');}finally{setBusy(false);}
 }
 function chooseTemplate(value:AnnouncementTemplate){setTemplate(value);if(!body&&!subject&&data?.event){const title=data.event.title;if(value==='reminder'){setSubject(`A little reminder · ${title}`);setBody('Your plans are coming together. Here are the event details from your host.\n\nWe’re looking forward to seeing you.');}else if(value==='thanks'){setSubject(`Thank you · ${title}`);setBody('Thank you for being part of this one. We hope you had a good time.\n\nUntil the next time we’re outside together.');}}}
 const used=data?Math.max(data.state?.contactCount??0,data.state?.reservedCount??0):0,ready=data?.configured&&data.state?.status==='ready';
 return <section className="event-audience announcement-composer" aria-label="Email announcements">
  <header className="campaign-overview"><div><h3>Updates from your host</h3><p>{data?.subscribed??0} subscribed guests · {data?.synced??0} ready for email</p></div><span className="campaign-allowance">{data?.state?.checkedAt?`${used.toLocaleString()} / 1,000`:'Checking…'}<small>Shared contact allowance</small></span></header>
  <p className="audience-closed-note">One email address uses one contact across events. Only guests who opted in receive announcements. RSVP and ticket emails are separate.</p>
  {used>=1000?<p role="status">The contact cap is reached. New RSVPs are still saved; new marketing imports are paused.</p>:null}
  {!ready?<p role="status">{data?.state?.error??'Connecting marketing emails. You can write and preview your announcement while we check.'}</p>:null}
  <div className="campaign-options"><label>Template<select value={template} disabled={busy||!!preview} onChange={e=>chooseTemplate(e.target.value as AnnouncementTemplate)}>{Object.entries(announcementTemplates).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label>Audience<select value={audience} disabled={busy||!!preview} onChange={e=>setAudience(e.target.value as MarketingAudience)}>{Object.entries(marketingAudiences).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
  <label>Subject<input maxLength={120} value={subject} disabled={busy||!!preview} onChange={e=>setSubject(e.target.value)}/></label>
  <label>Announcement<textarea maxLength={5000} rows={6} value={body} disabled={busy||!!preview} onChange={e=>setBody(e.target.value)}/></label>
  <label>Schedule (optional, Ghana time)<input type="datetime-local" value={scheduledAt} disabled={busy||!!preview} onChange={e=>setScheduledAt(e.target.value)}/><small>Leave empty to queue now. Scheduled sends begin at this time and can take a few minutes to prepare.</small></label>
  {preview?<section className="announcement-preview"><p>This goes to {preview.recipients} subscribed guest emails. Each email includes an unsubscribe link.</p><p>{scheduledAt?`Scheduled for ${scheduledAt.replace('T',' ')} · Ghana time`:'Ready to queue now'}</p><div className="campaign-email-preview" aria-label="Branded email preview" dangerouslySetInnerHTML={{__html:preview.html.replaceAll('{{{RESEND_UNSUBSCRIBE_URL}}}','#')}}/><div className="registration-actions"><ActionButton variant="secondary" disabled={busy} onClick={()=>setPreview(null)}>Edit message</ActionButton><ActionButton disabled={busy||!ready||!preview.recipients} onClick={()=>void act('send')}>{busy?'Saving…':scheduledAt?'Schedule announcement':'Send announcement'}</ActionButton></div></section>:<ActionButton disabled={busy||subject.trim().length<3||body.trim().length<10} onClick={()=>void act('preview')}>{busy?'Preparing preview…':'Preview announcement'}</ActionButton>}
  {message?<p className="ops-message" role="status">{message}</p>:null}
  <details className="announcement-history"><summary>Previous announcements · {data?.campaigns.length??0}</summary><button onClick={()=>void load()}>Refresh status</button>{data?.campaigns.map(c=><article key={c.id}><b>{c.subject}</b><p>{statusLabels[c.status]??c.status} · {c.recipientCount} selected contacts</p>{c.status==='queued'?<p>{new Date(c.scheduledAt).toLocaleString('en-GH',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Accra'})} · Ghana time</p>:null}{c.metricsAt?<p>{c.metrics.sent??0} sent · {c.metrics.delivered??0} delivered · {c.metrics.bounced??0} bounced · {c.metrics.complained??0} complaints</p>:c.status==='sent'?<p>Delivery results are pending. Counts can take 20 minutes to update.</p>:null}{c.error?<p>{c.error}</p>:null}{['queued','preparing'].includes(c.status)?<ActionButton variant="text" disabled={busy} onClick={()=>void act('cancel',c.id)}>Cancel announcement</ActionButton>:null}</article>)}{!data?.campaigns.length?<p>No announcements yet.</p>:null}</details>
 </section>;
}
