'use client';
import {useCallback,useEffect,useState} from 'react';
import {operationsFetch} from '../lib/operations-client';
type Contact={email:string;name:string;guests:number;source:string;subscribed:number};
type Campaign={id:string;subject:string;status:string;recipientCount:number;sent:number;failed:number;createdAt:string};
export default function EventAudience({eventSlug,view}:{eventSlug:string;view:'guests'|'announcements'}){
 const [contacts,setContacts]=useState<Contact[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[total,setTotal]=useState(0),[subscribers,setSubscribers]=useState(0),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[preview,setPreview]=useState(false),[sendId,setSendId]=useState('');
 const load=useCallback(async()=>{const r=await operationsFetch(`/api/admin/audience?eventSlug=${encodeURIComponent(eventSlug)}&q=${encodeURIComponent(query)}&offset=${offset}`);const d=await r.json() as {contacts?:Contact[];campaigns?:Campaign[];total?:number;subscribers?:number;emailConfigured?:boolean;error?:string};if(!r.ok){setMessage(d.error??'The guest list could not load.');return;}setContacts(d.contacts??[]);setCampaigns(d.campaigns??[]);setTotal(d.total??0);setSubscribers(d.subscribers??0);setConfigured(Boolean(d.emailConfigured));},[eventSlug,query,offset]);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;async function refresh(){if(!document.hidden)await load();if(!stopped)timer=setTimeout(refresh,10000);}void refresh();return()=>{stopped=true;clearTimeout(timer);};},[load]);
 async function send(){if(busy)return;setBusy(true);setMessage('');const r=await operationsFetch('/api/admin/audience',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventSlug,id:sendId,subject,body})});const d=await r.json() as {error?:string;recipients?:number};if(r.ok){setMessage('Announcement queued. Delivery progress appears below and the owner is notified.');setSubject('');setBody('');setPreview(false);setSendId('');await load();}else setMessage(d.error??'The announcement did not queue.');setBusy(false);}
 return <section className="event-audience" aria-label={view==='guests'?'Guest email list':'Email announcements'}>{view==='guests'?<><header><div><b>{total} guest emails</b><p>Free RSVP and paid registrations are stored together. {subscribers} have subscribed to announcements.</p></div><a href={`/api/admin/audience?eventSlug=${encodeURIComponent(eventSlug)}&q=${encodeURIComponent(query)}&export=csv`}>Export CSV</a></header><label>Search guest emails<input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder="Name or email" /></label><div className="audience-list">{contacts.map(c=><article key={c.email}><div><b>{c.name}</b><span>{c.email}</span></div><small>{c.source.replace('rsvp','Free RSVP').replace('paid','Paid registration').replace('interest','Email list')} · {c.subscribed?'Subscribed':'Booking emails only'}</small></article>)}{!contacts.length?<p>No guests match this view yet.</p>:null}</div><div className="registration-actions"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><span>{total?offset+1:0}–{Math.min(offset+50,total)} of {total}</span><button disabled={offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</button></div></>:<><p>Send an email to the guests who subscribed to this event’s announcements. Your owner dashboard records each send.</p>{!configured?<p>Email delivery is not configured yet. Guest emails remain stored.</p>:null}<label>Subject<input maxLength={120} value={subject} disabled={busy||preview} onChange={e=>setSubject(e.target.value)} /></label><label>Announcement<textarea maxLength={5000} value={body} disabled={busy||preview} onChange={e=>setBody(e.target.value)} rows={5} /></label>{preview?<section className="announcement-preview"><b>{subject}</b><p>{body}</p><p>This goes to {subscribers} subscribed guest emails. Each email includes an unsubscribe link.</p><div className="registration-actions"><button disabled={busy} onClick={()=>setPreview(false)}>Edit message</button><button disabled={busy} onClick={()=>void send()}>{busy?'Queuing…':'Send announcement'}</button></div></section>:<button disabled={!configured||!subscribers||subject.trim().length<3||body.trim().length<10} onClick={()=>{setPreview(true);setSendId(crypto.randomUUID());}}>Preview announcement</button>}<header><h3>Sent & queued announcements</h3><button onClick={()=>void load()}>Refresh delivery status</button></header>{campaigns.map(c=><article key={c.id}><b>{c.subject}</b><p>{c.sent} of {c.recipientCount} accepted by email provider · {c.status}{c.failed?` · ${c.failed} need delivery retry`:''}</p></article>)}{!campaigns.length?<p>No email announcements yet.</p>:null}</>}{message?<p role="status">{message}</p>:null}</section>;
}
