'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Download,Search,UsersRound} from 'lucide-react';
import {ActionButton} from './action';
import {operationsFetch} from '../lib/operations-client';
type Contact={email:string;name:string;guests:number;source:string;subscribed:number};
type Campaign={id:string;subject:string;status:string;recipientCount:number;sent:number;failed:number;createdAt:string};
const pageSize=10;
export default function EventAudience({eventSlug,view}:{eventSlug:string;view:'guests'|'announcements'}){
 const [contacts,setContacts]=useState<Contact[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[total,setTotal]=useState(0),[subscribers,setSubscribers]=useState(0),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[preview,setPreview]=useState(false),[sendId,setSendId]=useState(''),[showContacts,setShowContacts]=useState(false),[loading,setLoading]=useState(true);
 const generation=useRef(0);
 const load=useCallback(async()=>{const current=++generation.current;try{const r=await operationsFetch(`/api/admin/audience?eventSlug=${encodeURIComponent(eventSlug)}&q=${encodeURIComponent(query)}&offset=${offset}&limit=${pageSize}&summary=${showContacts?'0':'1'}`);const d=await r.json() as {contacts?:Contact[];campaigns?:Campaign[];total?:number;subscribers?:number;emailConfigured?:boolean;error?:string};if(current!==generation.current)return;if(!r.ok){setMessage(d.error??'The guest list could not load.');return;}setContacts(d.contacts??[]);setCampaigns(d.campaigns??[]);setTotal(d.total??0);setSubscribers(d.subscribers??0);setConfigured(Boolean(d.emailConfigured));}catch{if(current===generation.current)setMessage('Couldn’t load guest emails. Try again.');}finally{if(current===generation.current)setLoading(false);}},[eventSlug,query,offset,showContacts]);
 useEffect(()=>{const invalidate=()=>{++generation.current;};let stopped=false,timer:ReturnType<typeof setTimeout>;async function refresh(){if(!document.hidden)await load();if(!stopped)timer=setTimeout(refresh,10000);}timer=setTimeout(refresh,180);return()=>{stopped=true;invalidate();clearTimeout(timer);};},[load]);
 async function send(){if(busy)return;setBusy(true);setMessage('');try{const r=await operationsFetch('/api/admin/audience',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventSlug,id:sendId,subject,body})});const d=await r.json() as {error?:string};if(r.ok){setMessage('Your announcement is on its way.');setSubject('');setBody('');setPreview(false);setSendId('');await load();}else setMessage(d.error??'The announcement couldn’t be sent. Try again.');}catch{setMessage('Connection lost. Your message is still here. Try again.');}finally{setBusy(false);}}
 return <section className="event-audience" aria-label={view==='guests'?'Guest email list':'Email announcements'}>{view==='guests'?<>
  <header className="audience-overview"><UsersRound size={22}/><div><h3>{loading||query.trim()?'Guest emails':`${total} guest email${total===1?'':'s'}`}</h3><p>{subscribers} signed up for announcements.</p></div><a className="audience-export" href={`/api/admin/audience?eventSlug=${encodeURIComponent(eventSlug)}&q=${encodeURIComponent(query)}&export=csv`}><Download size={16}/> Export CSV</a></header>
  <div className="audience-tools"><label><span>Search guest emails</span><span className="audience-search"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);setShowContacts(Boolean(e.target.value.trim()));}} placeholder="Find someone by name or email" /></span></label><ActionButton variant="secondary" disabled={loading} onClick={()=>{setShowContacts(!showContacts);setQuery('');setOffset(0);}}>{showContacts?'Close email list':'View guest emails'}</ActionButton></div>
  {showContacts?<><div className="audience-table" role="region" aria-label="Guest email results" tabIndex={0}><table><thead><tr><th>Guest</th><th>Email</th><th>Announcements</th></tr></thead><tbody>{contacts.map(c=><tr key={c.email}><td>{c.name}</td><td><a href={`mailto:${c.email}`}>{c.email}</a></td><td>{c.subscribed?'Subscribed':'Not subscribed'}</td></tr>)}</tbody></table>{!contacts.length?<p>No matching guests yet.</p>:null}</div><div className="audience-pagination"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-pageSize))}>Previous</button><span>{total?offset+1:0}–{Math.min(offset+pageSize,total)} of {total}</span><button disabled={offset+pageSize>=total} onClick={()=>setOffset(offset+pageSize)}>Next</button></div></>:<p className="audience-closed-note">Guest emails are saved here. Open the list or search for someone when you need them.</p>}
 </>:<><p>Send an update to guests who signed up for announcements.</p>{!configured?<p>Email announcements aren’t available yet. Your guest emails are saved.</p>:null}<label>Subject<input maxLength={120} value={subject} disabled={busy||preview} onChange={e=>setSubject(e.target.value)} /></label><label>Announcement<textarea maxLength={5000} value={body} disabled={busy||preview} onChange={e=>setBody(e.target.value)} rows={5} /></label>{preview?<section className="announcement-preview"><b>{subject}</b><p>{body}</p><p>This goes to {subscribers} subscribed guest emails. Each email includes an unsubscribe link.</p><div className="registration-actions"><ActionButton variant="secondary" disabled={busy} onClick={()=>setPreview(false)}>Edit message</ActionButton><ActionButton disabled={busy} onClick={()=>void send()}>{busy?'Sending…':'Send announcement'}</ActionButton></div></section>:<ActionButton disabled={!configured||!subscribers||subject.trim().length<3||body.trim().length<10} onClick={()=>{setPreview(true);setSendId(crypto.randomUUID());}}>Preview announcement</ActionButton>}<details className="announcement-history"><summary>Previous announcements · {campaigns.length}</summary><button onClick={()=>void load()}>Refresh status</button>{campaigns.map(c=><article key={c.id}><b>{c.subject}</b><p>{c.sent} of {c.recipientCount} sent{c.failed?` · ${c.failed} couldn’t be sent`:''}</p></article>)}{!campaigns.length?<p>No announcements yet.</p>:null}</details></>}{message?<p className="ops-message" role="status">{message}</p>:null}</section>;
}
