'use client';
import { useCallback, useEffect, useState } from 'react';
type Settings = { mode: string; capacity: number; maxPartySize: number; approvalRequired: number; roomAccess: number };
type Row = { id: string; guestName: string; email: string; partySize: number; kind: string; status: string };
export default function RegistrationManager({ eventSlug }: { eventSlug: string }) {
  const [settings, setSettings] = useState<Settings | null>(null), [rows, setRows] = useState<Row[]>([]), [counts, setCounts] = useState<Array<{ status: string; guests: number; registrations: number }>>([]), [offset, setOffset] = useState(0), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const load = useCallback(() => fetch(`/api/admin/registrations?eventSlug=${encodeURIComponent(eventSlug)}&offset=${offset}`, { cache: 'no-store' }).then(async response => {
    const data = await response.json() as { error?: string; settings: Settings; registrations: Row[]; counts: Array<{ status: string; guests: number; registrations: number }> };
    if (!response.ok) throw new Error(data.error ?? 'Could not load registrations.');
    setSettings(data.settings); setRows(data.registrations); setCounts(data.counts);
  }).catch(error => setMessage(error instanceof Error ? error.message : 'Could not connect.')), [eventSlug, offset]);
  useEffect(() => { void load(); }, [load]);
  async function save(action: string, id?: string) {
    if (busy || !settings) return; setBusy(true); setMessage('');
    try { const response = await fetch('/api/admin/registrations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...settings, eventSlug, action, id, approvalRequired: Boolean(settings.approvalRequired), roomAccess: Boolean(settings.roomAccess) }) }); const data = await response.json() as { error?: string; settings: Settings; registrations: Row[]; counts: Array<{ status: string; guests: number; registrations: number }> }; if (!response.ok) throw new Error(data.error ?? 'Could not save.'); await load(); setMessage('Registration updated.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Could not connect.'); } finally { setBusy(false); }
  }
  return <details className="registration-manager"><summary>RSVP & registration</summary>{settings ? <><div className="registration-settings"><label>Entry mode<select value={settings.mode} onChange={e => setSettings({ ...settings, mode: e.target.value })}><option value="paid">Paid tickets</option><option value="rsvp">Free RSVP</option><option value="interest">Announcements only</option></select></label>{settings.mode === 'rsvp' ? <><label>Guest capacity<input type="number" min={1} max={50000} value={settings.capacity} onChange={e => setSettings({ ...settings, capacity: Number(e.target.value) })} /></label><label>Maximum party size<select value={settings.maxPartySize} onChange={e => setSettings({ ...settings, maxPartySize: Number(e.target.value) })}>{Array.from({ length: 10 }, (_, i) => <option key={i} value={i + 1}>{i + 1}</option>)}</select></label><label className="registration-consent"><input type="checkbox" checked={Boolean(settings.approvalRequired)} onChange={e => setSettings({ ...settings, approvalRequired: Number(e.target.checked) })} /> Require host approval</label><label className="registration-consent"><input type="checkbox" checked={Boolean(settings.roomAccess)} onChange={e => setSettings({ ...settings, roomAccess: Number(e.target.checked) })} /> Give confirmed RSVP guests Room access</label></> : null}<button disabled={busy} onClick={() => void save('settings')}>{busy ? 'Saving…' : 'Save registration settings'}</button></div><p>{counts.map(c => `${c.status}: ${c.guests} guests`).join(' · ') || 'No confirmed email registrations yet.'}</p><div className="registration-roster">{rows.map(row => <article key={row.id}><div><b>{row.guestName}</b><span>{row.email}</span><small>{row.status} · {row.partySize} guests</small></div><div className="registration-actions">{row.status === 'requested' ? <button disabled={busy} onClick={() => void save('approve', row.id)}>Approve</button> : null}{['requested', 'waitlisted'].includes(row.status) ? <button disabled={busy} onClick={() => void save('decline', row.id)}>Decline</button> : null}{row.status === 'confirmed' ? <button disabled={busy} onClick={() => void save('cancel', row.id)}>Cancel RSVP</button> : null}</div></article>)}</div><div className="registration-actions"><button disabled={busy || offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</button><button disabled={busy || rows.length < 50} onClick={() => setOffset(offset + 50)}>Next</button></div></> : <p>Loading registration settings…</p>}{message ? <p role="status">{message} <button onClick={() => void load()}>Refresh</button></p> : null}</details>;
}
