'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Check,Settings2,Users,Mail,Send,Save,CalendarClock} from 'lucide-react';
import {operationsFetch} from '../lib/operations-client';
import {ActionButton} from './action';
import RegistrationLive from './registration-live';
import EventAudience from './event-audience';
type Settings={mode:string;capacity:number;maxPartySize:number;approvalRequired:number;roomAccess:number;startsAt?:string;priceMinor?:number;accepting?:number;closesAt?:string|null;notifyHost?:number};
type Draft=Omit<Settings,'capacity'|'priceMinor'> & {capacity:string;price:string};
type Row={id:string;guestName:string;email:string;partySize:number;kind:string;status:string};
const statusNames:Record<string,string>={requested:'Needs approval',confirmed:'Confirmed',waitlisted:'Waitlisted',declined:'Declined',cancelled:'Cancelled',interested:'Email list'};
function draftOf(s:Settings,pricing?:{priceMinor:number;capacity:number}|null):Draft{return {...s,capacity:String(s.capacity||pricing?.capacity||100),price:String((pricing?.priceMinor??0)/100)};}
export default function RegistrationManager({eventSlug,expanded=false}:{eventSlug:string;expanded?:boolean}){
 const [view,setView]=useState('settings'),[settings,setSettings]=useState<Draft|null>(null),[saved,setSaved]=useState(''),[rows,setRows]=useState<Row[]>([]),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[total,setTotal]=useState(0),[counts,setCounts]=useState<{status:string;guests:number}[]>([]);
 const saving=useRef(false),revision=useRef(0),loadedEvent=useRef('');
 const load=useCallback(async(preserveDraft=true)=>{const version=++revision.current;const r=await operationsFetch(`/api/admin/registrations?eventSlug=${encodeURIComponent(eventSlug)}&offset=${offset}&q=${encodeURIComponent(query)}&status=${filter}`);const d=await r.json() as {error?:string;settings:Settings;registrations:Row[];total?:number;counts:{status:string;guests:number}[];pricing?:{priceMinor:number;capacity:number}|null};if(version!==revision.current)return;if(!r.ok){setMessage(d.error??'Could not load registrations.');return;}if(!preserveDraft||loadedEvent.current!==eventSlug){const draft=draftOf(d.settings,d.pricing);setSettings(draft);setSaved(JSON.stringify(draft));loadedEvent.current=eventSlug;}setRows(d.registrations);setCounts(d.counts);setTotal(d.total??d.registrations.length);},[eventSlug,offset,query,filter]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>{clearTimeout(timer);};},[load]);
 const dirty=Boolean(settings&&JSON.stringify(settings)!==saved);
 async function save(action='settings',id?:string):Promise<boolean>{
  if(saving.current||!settings)return false;
  if(action==='settings'&&settings.mode!=='interest'&&(!settings.capacity.trim()||!Number.isInteger(Number(settings.capacity))||Number(settings.capacity)<1)){setMessage('Enter a guest capacity of at least 1.');return false;}
  if(action==='settings'&&settings.mode==='paid'&&(!settings.price.trim()||!Number.isFinite(Number(settings.price))||Number(settings.price)<1)){setMessage('Enter a registration price of at least GHS 1.');return false;}
  saving.current=true;setBusy(true);setMessage('');
  try{const r=await operationsFetch('/api/admin/registrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...settings,capacity:Number(settings.capacity),priceMinor:Math.round(Number(settings.price)*100),eventSlug,action,id,approvalRequired:Boolean(settings.approvalRequired),roomAccess:Boolean(settings.roomAccess),accepting:settings.accepting!==0,notifyHost:settings.notifyHost!==0})});const d=await r.json() as {error?:string};if(!r.ok){setMessage(d.error??'Could not save.');return false;}if(action==='settings')setSaved(JSON.stringify(settings));await load();setMessage(action==='settings'?'Registration settings saved.':'Guest registration updated.');return true;}finally{saving.current=false;setBusy(false);}
 }
 function midnight(){if(!settings?.startsAt)return;const date=new Date(settings.startsAt);if(!Number.isFinite(date.getTime()))return;date.setUTCHours(0,0,0,0);setSettings({...settings,closesAt:date.toISOString()});}
 const pending=counts.find(c=>c.status==='requested')?.guests??0;
 return <details className="registration-manager" open={expanded||undefined}><summary>RSVP & guests</summary>
 <RegistrationLive eventSlug={eventSlug} onChange={()=>void load()} hasUnsavedChanges={dirty} settingsVersion={saved} onSave={()=>save()} busy={busy} />
 <nav className="ops-tabs" aria-label="Registration tools">{[{key:'settings',label:'Setup',Icon:Settings2},{key:'roster',label:`Guest list${pending?` · ${pending} to review`:''}`,Icon:Users},{key:'guests',label:'Guest emails',Icon:Mail},{key:'announcements',label:'Announcements',Icon:Send}].map(({key,label,Icon})=><button key={key} aria-pressed={view===key} onClick={()=>setView(key)}><Icon size={16}/>{label}</button>)}</nav>
 {view==='settings'?settings?<section className="registration-setup"><header><h3>How should guests join?</h3><span>{dirty?'Unsaved changes':'Saved setup'}</span></header>
 <div className="registration-mode-choices">{[['rsvp','RSVP','No ticket payment'],['paid','Paid registration','Tickets at checkout'],['interest','Email list only','Updates, without admission']].map(([mode,title,description])=><button key={mode} disabled={busy} aria-pressed={settings.mode===mode} onClick={()=>setSettings({...settings,mode})}><b>{title}</b><span>{description}</span>{settings.mode===mode?<Check size={16} aria-hidden="true"/>:null}</button>)}</div>
 <div className="registration-settings">
 {settings.mode!=='interest'?<label>{settings.mode==='paid'?'Base tier capacity':'Guest capacity'}<input type="number" min={1} max={50000} value={settings.capacity} onChange={e=>setSettings({...settings,capacity:e.target.value})}/></label>:null}
 {settings.mode==='paid'?<label>Base registration price (GHS)<input type="number" min={1} step="0.01" max={100000} value={settings.price} onChange={e=>setSettings({...settings,price:e.target.value})}/></label>:null}
 {settings.mode==='rsvp'?<label>Guests per RSVP<select value={settings.maxPartySize} onChange={e=>setSettings({...settings,maxPartySize:Number(e.target.value)})}>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>:null}
 <label className="registration-deadline">Registration deadline (Accra time)<input type="datetime-local" value={settings.closesAt?.slice(0,16)??''} onChange={e=>setSettings({...settings,closesAt:e.target.value?`${e.target.value}:00.000Z`:null})}/>{settings.startsAt?<button type="button" onClick={midnight}><CalendarClock size={14}/>Midnight before the event</button>:null}</label>
 {settings.mode==='rsvp'?<label className="registration-consent"><input type="checkbox" role="switch" checked={Boolean(settings.approvalRequired)} onChange={e=>setSettings({...settings,approvalRequired:Number(e.target.checked)})}/><span>Review requests before confirming guests</span></label>:null}
 <label className="registration-consent"><input type="checkbox" role="switch" checked={settings.accepting!==0} onChange={e=>setSettings({...settings,accepting:Number(e.target.checked)})}/><span>Accept new registrations</span></label>
 </div>
 <details className="registration-options"><summary>More options</summary><label className="registration-consent"><input type="checkbox" role="switch" checked={settings.notifyHost!==0} onChange={e=>setSettings({...settings,notifyHost:Number(e.target.checked)})}/><span>Email assigned organisers when a guest signs up</span></label>{settings.mode==='rsvp'?<label className="registration-consent"><input type="checkbox" role="switch" checked={Boolean(settings.roomAccess)} onChange={e=>setSettings({...settings,roomAccess:Number(e.target.checked)})}/><span>Give confirmed guests access to The Room</span></label>:null}</details>
 <ActionButton disabled={busy} icon={<Save size={16}/>} onClick={()=>void save()}>{busy?'Saving…':'Save registration settings'}</ActionButton>
 </section>:<p>Loading registration settings…</p>:view==='roster'?<section className="registration-guest-list"><header><h3>Guest list</h3><span>{total} requests</span></header><div className="registration-roster-tools"><label>Find a guest<input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder="Name or email"/></label><label>Status<select value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">All guests</option>{Object.entries(statusNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
 <div className="registration-roster">{rows.map(row=><article key={row.id}><div><b>{row.guestName}</b><span>{row.email}</span></div><small data-status={row.status}>{statusNames[row.status]??row.status} · {row.partySize} {row.partySize===1?'guest':'guests'}</small><div className="registration-actions">{row.status==='requested'?<ActionButton disabled={busy} icon={<Check size={15}/>} onClick={()=>void save('approve',row.id)}>Approve</ActionButton>:null}{['requested','waitlisted'].includes(row.status)?<button disabled={busy} onClick={()=>void save('decline',row.id)}>Decline</button>:null}{row.status==='confirmed'?<button disabled={busy} onClick={()=>void save('cancel',row.id)}>Cancel RSVP</button>:null}</div></article>)}{!rows.length?<p className="ops-empty">{query||filter?'No guests match this view.':'Share your link. Guest requests will appear here.'}</p>:null}</div>
 <nav className="order-pagination" aria-label="Guest pages"><span>{total?offset+1:0}–{Math.min(offset+50,total)} of {total}</span><div><button disabled={busy||!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={busy||offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</button></div></nav></section>:<EventAudience key={view} eventSlug={eventSlug} view={view as 'guests'|'announcements'}/>}
 {message?<p className="ops-message" role="status">{message}</p>:null}</details>;
}
