export const announcementTemplates = {
 update: { label: 'Event update', kicker: 'FROM YOUR HOST', cta: 'View event' },
 reminder: { label: 'Event reminder', kicker: 'SEE YOU SOON', cta: 'View event details' },
 thanks: { label: 'Thank you', kicker: 'THAT WAS A GOOD ONE', cta: 'Revisit the event' },
} as const;
export type AnnouncementTemplate = keyof typeof announcementTemplates;
export type AnnouncementEvent = { title:string; slug:string; venue:string; startsAt:string; scheduleStatus:string; scheduleLabel:string|null; imageUrl:string };
const escape = (s:string) => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;').replaceAll('{','&#123;').replaceAll('}','&#125;');
export function renderAnnouncement(event:AnnouncementEvent, subject:string, body:string, template:AnnouncementTemplate, origin='https://tickets.becoreops.com') {
 const theme=announcementTemplates[template],url=`${origin}/event/${encodeURIComponent(event.slug)}`;
 const date=event.scheduleStatus==='coming_soon' ? event.scheduleLabel || 'Date to be announced' : new Date(event.startsAt).toLocaleString('en-GH',{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Accra'})+' · Ghana time';
 let image='';try {const parsed=new URL(event.imageUrl,origin);if(parsed.protocol==='https:'&&(parsed.origin===origin||parsed.hostname==='images.unsplash.com'))image=parsed.href;}catch{}
 const html=`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#e9e3e7;font-family:Arial,Helvetica,sans-serif;color:#281b2b"><tr><td align="center" style="padding:20px 8px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#faf6ef"><tr><td style="background:#281b2b;padding:26px 28px;color:#faf6ef"><img src="${origin}/brand/becore-ticket.png?v=5" alt="" width="40" height="43" style="vertical-align:middle;margin-right:12px"><span style="font-size:24px;font-weight:bold;vertical-align:middle">BeCore <span style="font-size:12px;letter-spacing:3px">TICKETS</span></span></td></tr><tr><td style="padding:32px 28px"><p style="font-size:11px;letter-spacing:2px">${theme.kicker}</p><h1 style="font-size:34px;line-height:1.1;margin:20px 0">${escape(subject)}</h1><p style="font-size:17px;line-height:1.7;overflow-wrap:anywhere">${escape(body).replaceAll('\n','<br>')}</p></td></tr><tr><td style="background:#f0dce3;padding:24px 28px"><h2 style="font-size:24px;margin:0 0 12px">${escape(event.title)}</h2><p style="line-height:1.6;margin:0">${escape(date)}<br>${escape(event.venue)}</p></td></tr>${image?`<tr><td align="center" style="padding:28px"><a href="${url}"><img src="${escape(image)}" alt="${escape(event.title)} flier" width="220" style="display:block;width:220px;max-width:100%;height:auto"></a></td></tr>`:''}<tr><td style="padding:28px;text-align:center"><a href="${url}" style="display:inline-block;background:#dbf568;color:#281b2b;text-decoration:none;padding:17px 28px;font-weight:bold;border-radius:4px">${theme.cta}</a></td></tr><tr><td style="background:#281b2b;color:#faf6ef;padding:28px;font-size:12px;line-height:1.7"><b style="font-size:20px">See you outside.</b><p>BeCore Tickets · Accra, after the group chat.</p><p>You signed up for updates from this event’s host.<br><a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#dbf568;text-decoration:underline">Unsubscribe from marketing emails</a>. Your RSVP or ticket stays valid.</p></td></tr></table></td></tr></table>`;
 return {html,text:`${subject}\n\n${body}\n\n${event.title}\n${date}\n${event.venue}\n${url}\n\nYou signed up for updates from this event’s host. Unsubscribe from marketing emails: {{{RESEND_UNSUBSCRIBE_URL}}}\nYour RSVP or ticket stays valid.`};
}
