'use client';
import {useState} from 'react';
import RegistrationManager from '../../registration-manager';
import {apiUrl,date,money,readable,useRemote,useMutation,RemoteState,Pager,Message} from './suite-shared';
type Statement={id:string;eventTitle:string;periodEnd:string;grossMinor:number;feesMinor:number;refundsMinor:number;netMinor:number;status:string};
type Transfer={id:string;reference:string;amountMinor:number;status:string;paidAt:string;createdAt:string;accountName:string;accountNumberMasked:string};
export function Money({event}:{event:string}){
 const r=useRemote<{totals:{collectedMinor:number;feesMinor:number;refundsMinor:number;faceMinor:number;ticketRefundsMinor:number};payoutTotals:{paidMinor:number;pendingMinor:number};statements:Statement[];transfers:Transfer[]}>('money',event);
 const d=r.data,paid=d?.payoutTotals.paidMinor??0;
 return <section className="suite-section"><header><div><p className="suite-eyebrow">Money</p><h2>Know where you stand.</h2><p>Collected payments, refunds and confirmed transfers. All amounts in GHS.</p></div><a className="suite-button" href={apiUrl('money',event,'format=csv')}>Export statements</a></header><RemoteState error={r.error} loading={!d} refresh={r.refresh}/>{d?<><div className="suite-stats">{[['Collected',d.totals.collectedMinor],['Booking fees',d.totals.feesMinor],['Refunds',d.totals.refundsMinor],['Ticket value after refunds',d.totals.faceMinor-d.totals.ticketRefundsMinor],['Paid out',paid]].map(([label,n])=><article key={label}><span>{label}</span><b>{money(Number(n))}</b></article>)}</div><p className="suite-note">Ticket value is an accounting total. Statements and transfer status below show what BeCore has approved and paid.</p><h3>Settlement statements</h3><div className="suite-table" tabIndex={0} role="region" aria-label="Settlement statements"><table><thead><tr><th>Event / period end</th><th>Collected</th><th>Fees</th><th>Refunds</th><th>Net tickets</th><th>Status</th></tr></thead><tbody>{d.statements.map(x=><tr key={x.id}><td>{x.eventTitle}<small>{date(x.periodEnd)}</small></td><td>{money(x.grossMinor)}</td><td>{money(x.feesMinor)}</td><td>{money(x.refundsMinor)}</td><td>{money(x.netMinor)}</td><td>{readable(x.status)}</td></tr>)}</tbody></table>{!d.statements.length?<p>No settlement statements yet.</p>:null}</div><h3>Payout history</h3><div className="suite-rows">{d.transfers.map(x=><article key={x.id}><div><b>{money(x.amountMinor)}</b><p>{x.accountName} · {x.accountNumberMasked}</p><small>{x.reference} · {date(x.paidAt??x.createdAt)}</small></div><span className="suite-badge">{readable(x.status)}</span></article>)}{!d.transfers.length?<p>No transfers yet. Approved payouts will appear here.</p>:null}</div><p className="suite-note">Showing the latest 250 statements and transfers. For a payment query, open Help in your event.</p></>:null}</section>;
}
type Guest={id:string;kind:string;name:string;email:string;reference:string;status:string;admissions:number;arrivals:number;amountMinor:number;source:string};
type Details={record:Guest;orderId:string|null;tickets:{id:string;ticketType:string;status:string;holderName:string;holderEmail:string;checkedInAt:string|null}[];delivery:{kind:string;status:string;updatedAt:string}[];confirmation:{status:string;updatedAt:string}|null;questions:{name:string;prompt:string;answer:string}[]};
function GuestDetail({event,guest,onClose}:{event:string;guest:Guest;onClose:()=>void}){
 const r=useRemote<Details>('guest_detail',event,new URLSearchParams({kind:guest.kind,id:guest.id}).toString()),m=useMutation(),[refund,setRefund]=useState(false),[reason,setReason]=useState('');const d=r.data;
 return <section className="suite-detail" aria-label="Guest record"><header><h3>{guest.name}</h3><button onClick={onClose}>Close record</button></header><RemoteState error={r.error} loading={!d} refresh={r.refresh}/>{d?<><p>{d.record.email} · {readable(d.record.source)} · {d.record.reference||'Guest registration'}</p><div className="suite-stats"><article><span>Booking state</span><b>{readable(d.record.status)}</b></article><article><span>Arrival</span><b>{d.record.arrivals} / {d.record.admissions}</b></article><article><span>Order total</span><b>{money(d.record.amountMinor)}</b></article></div>{d.tickets.map(t=><article className="suite-ticket" key={t.id}><div><b>{t.holderName??'Guest'}</b><p>{t.holderEmail??'No active holder'} · {readable(t.status)}</p>{t.checkedInAt?<small>Arrived {date(t.checkedInAt)}</small>:null}</div>{['issued','checked_in'].includes(t.status)&&t.holderEmail?<button disabled={m.busy} onClick={async()=>{if(await m.mutate({action:'guest_recovery',eventSlug:event,ticketId:t.id})){m.setMessage('A private My Nights link is queued for the current holder.');r.refresh();}}}>Resend access</button>:null}</article>)}<details><summary>Delivery & guest answers</summary><p>Confirmation: {readable(d.confirmation?.status??'No confirmation recorded')}</p>{d.delivery.map((x,i)=><p key={i}>{readable(x.kind)} · {readable(x.status)} · {date(x.updatedAt)}</p>)}{d.questions.map((x,i)=><p key={i}><b>{x.name} · {x.prompt}</b><br/>{x.answer}</p>)}</details>{d.orderId&&d.record.amountMinor>0?<button onClick={()=>setRefund(!refund)}>Request a refund review</button>:null}{refund?<form onSubmit={async e=>{e.preventDefault();if(await m.mutate({action:'request',eventSlug:event,kind:'refund_order',orderId:d.orderId,detail:reason},'/api/organizer/workspace')){setRefund(false);setReason('');m.setMessage('Refund request sent to BeCore for review.');}}}><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={1200} required/></label><button disabled={m.busy}>Send refund request</button></form>:null}</>:null}<Message>{m.message}</Message></section>;
}
export function Guests({event}:{event:string}){
 const [view,setView]=useState('records'),[visited,setVisited]=useState(false),[q,setQ]=useState(''),[status,setStatus]=useState(''),[show,setShow]=useState(false),[offset,setOffset]=useState(0),[guest,setGuest]=useState<Guest|null>(null);
 const extra=new URLSearchParams({q,status,show:show?'1':'0',offset:String(offset)}).toString(),r=useRemote<{counts:{records:number;admissions:number;arrivals:number};rows:Guest[]}>('guests',event,extra),d=r.data;
 return <section className="suite-section"><header><div><p className="suite-eyebrow">Guests</p><h2>One guest desk.</h2><p>Find paid tickets, RSVPs, complimentary passes and door entries together.</p></div><a className="suite-button" href={apiUrl('guests',event,extra+'&format=csv')}>Export guests</a></header><div className="suite-segments" aria-label="Guest tools"><button aria-pressed={view==='records'} onClick={()=>setView('records')}>All records</button><button aria-pressed={view==='rsvp'} onClick={()=>{setView('rsvp');setVisited(true);}}>RSVP review & setup</button></div><div hidden={view!=='records'}><RemoteState error={r.error} loading={!d} refresh={r.refresh}/>{d?<><div className="suite-stats"><article><span>Booking & guest records</span><b>{d.counts.records}</b></article><article><span>Checked in</span><b>{d.counts.arrivals}</b></article></div><div className="suite-filters"><label>Find a guest<input type="search" value={q} placeholder="Name, email or booking reference" onChange={e=>{setQ(e.target.value);setOffset(0);setGuest(null);}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">All statuses</option>{['paid','payment_pending','confirmed','requested','waitlisted','interested','declined','cancelled','refunded','checked_in'].map(x=><option key={x} value={x}>{readable(x)}</option>)}</select></label><button onClick={()=>{setShow(!show);setGuest(null);}}>{show?'Hide list':'View guests'}</button></div>{show||q?<><div className="suite-rows">{d.rows.map(x=><article key={`${x.kind}:${x.id}`}><div><b>{x.name}</b><p>{x.email}</p><small>{x.reference||readable(x.source)} · {readable(x.status)} · {x.arrivals}/{x.admissions} arrived</small></div><button onClick={()=>setGuest(x)}>Open record</button></article>)}{!d.rows.length?<p>No guests match this view.</p>:null}</div><Pager offset={offset} total={d.counts.records} onChange={setOffset}/></>:<p className="suite-note">Search for someone or open the list when you need guest details.</p>}{guest?<GuestDetail key={`${guest.kind}:${guest.id}`} guest={guest} event={event} onClose={()=>setGuest(null)}/>:null}</>:null}</div><div hidden={view!=='rsvp'}>{visited?<RegistrationManager eventSlug={event} expanded/>:null}</div></section>;
}
type Contact={email:string;name:string;events:number;vip:number;subscribed:number;lastSeen:string};
function ContactHistory({email,onClose}:{email:string;onClose:()=>void}){const r=useRemote<{rows:{slug:string;title:string;bookedAt:string;status:string;source:string;admissions:number;amountMinor:number}[]}>('audience_history','all',new URLSearchParams({email}).toString());return <section className="suite-detail"><header><h3>{email}</h3><button onClick={onClose}>Close history</button></header><RemoteState error={r.error} loading={!r.data} refresh={r.refresh}/>{r.data?.rows.map((x,i)=><article key={i}><b>{x.title}</b><p>{date(x.bookedAt)} · {readable(x.source)} · {readable(x.status)} · {x.admissions} guests</p></article>)}<p className="suite-note">History includes only your assigned events, up to 100 records.</p></section>;}
export function Audience(){
 const [q,setQ]=useState(''),[show,setShow]=useState(false),[segment,setSegment]=useState('all'),[offset,setOffset]=useState(0),[selected,setSelected]=useState('');const extra=new URLSearchParams({q,show:show?'1':'0',segment,offset:String(offset)}).toString(),r=useRemote<{totals:{total:number;subscribers:number};rows:Contact[]}>('audience','all',extra),d=r.data;
 return <section className="suite-section"><header><div><p className="suite-eyebrow">Audience</p><h2>Your crowd, over time.</h2><p>Guest history across the Nights you manage.</p></div><a className="suite-button" href={apiUrl('audience','all',extra+'&format=csv')}>Export audience</a></header><RemoteState error={r.error} loading={!d} refresh={r.refresh}/>{d?<><div className="suite-stats"><article><span>Guests in this group</span><b>{d.totals.total}</b></article><article><span>Subscribed to an event</span><b>{d.totals.subscribers}</b></article></div><div className="suite-filters"><label>Search guests<input type="search" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}} placeholder="Name or email"/></label><label>Group<select value={segment} onChange={e=>{setSegment(e.target.value);setOffset(0);}}><option value="all">All guests</option><option value="repeat">Repeat guests</option><option value="vip">VIP guests</option><option value="subscribers">Subscribers</option></select></label><button onClick={()=>setShow(!show)}>{show?'Hide audience':'View audience'}</button></div><p className="suite-note">Announcement consent belongs to each event. Send from Promote to reach only guests subscribed to the selected Night.</p>{show||q?<><div className="suite-rows">{d.rows.map(x=><article key={x.email}><div><b>{x.name}</b><p>{x.email}</p><small>{x.events} {x.events===1?'event':'events'} · {x.vip?'VIP · ':''}{x.subscribed?'Subscribed to an event':'No announcement subscription'}</small></div><button onClick={()=>setSelected(x.email)}>View history</button></article>)}{!d.rows.length?<p>No matching guests yet.</p>:null}</div><Pager offset={offset} total={d.totals.total} onChange={setOffset}/></>:null}{selected?<ContactHistory email={selected} onClose={()=>setSelected('')}/>:null}</>:null}</section>;
}
