'use client';
import {useState} from 'react';
import {parseComplimentaryCsv,type ComplimentaryRow} from '../../../lib/complimentary-csv';
import {money,useRemote,useMutation,RemoteState,Message,type Tier,type EventItem} from './suite-shared';
export function Tickets({event}:{event:string}){
 const r=useRemote<{tiers:Tier[]}>('tickets',event),m=useMutation(),[csv,setCsv]=useState(''),[tierId,setTierId]=useState(''),[preview,setPreview]=useState<{rows:ComplimentaryRow[];batchId:string;tierId:string}|null>(null),[results,setResults]=useState<Record<number,string>>({}),[issuing,setIssuing]=useState(false);
 async function review(){
  try{const rows=parseComplimentaryCsv(csv),tier=r.data?.tiers.find(t=>t.id===tierId);if(!tier)throw new Error('Choose a ticket type.');if(rows.reduce((n,x)=>n+x.quantity,0)>tier.capacity-tier.allocated)throw new Error('This list needs more admissions than the selected ticket type has available.');
   const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([event,tierId,rows])))),b=>b.toString(16).padStart(2,'0')).join('');let batchId=crypto.randomUUID() as string;
   try{const existing=sessionStorage.getItem(`comp:${hash}`);if(existing&&/^[a-f0-9-]{36}$/u.test(existing))batchId=existing;else sessionStorage.setItem(`comp:${hash}`,batchId);}catch{/* The same request IDs remain in memory for retries. */}
   setPreview({rows,batchId,tierId});setResults({});m.setMessage('Review each name, email and admission count before issuing.');
  }catch(e){m.setMessage(e instanceof Error?e.message:'Check the CSV.');}
 }
 async function issue(){if(!preview||issuing)return;setIssuing(true);try{for(let i=0;i<preview.rows.length;i++){if(results[i])continue;const result=await m.mutate({action:'complimentary',eventSlug:event,tierId:preview.tierId,...preview.rows[i],mutationId:`comp-${preview.batchId}-${i}`});if(!result)return;setResults(current=>({...current,[i]:String(result.reference)}));}m.setMessage('All complimentary passes are issued. Confirmation delivery is queued.');r.refresh();}finally{setIssuing(false);}}
 return <section className="suite-section"><header><div><p className="suite-eyebrow">Tickets</p><h2>A place for every guest.</h2><p>Capacity includes paid, held and complimentary admissions.</p></div></header><RemoteState error={r.error} loading={!r.data} refresh={r.refresh}/><div className="suite-rows">{r.data?.tiers.map(t=><article key={t.id}><div><b>{t.name}</b><p>{money(t.priceMinor)} · {t.admissionsPerUnit} admissions per package · {t.status}</p></div><span>{t.allocated} / {t.capacity} allocated</span></article>)}</div><details className="suite-disclosure"><summary>Issue complimentary passes</summary><p>Upload or paste a CSV with <code>name,email,quantity</code>. Quantity is admissions, including for group ticket types. Up to 100 guests, 20 admissions each.</p><label>Ticket type<select value={tierId} disabled={!!preview||issuing} onChange={e=>setTierId(e.target.value)}><option value="">Choose a ticket type</option>{r.data?.tiers.map(t=><option key={t.id} value={t.id}>{t.name} · {Math.max(0,t.capacity-t.allocated)} available</option>)}</select></label><label>CSV file<input type="file" accept=".csv,text/csv" disabled={!!preview||issuing} onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>100000){m.setMessage('Choose a CSV smaller than 100 KB.');return;}setCsv(await f.text());}}}/></label><label>Guest CSV<textarea rows={5} placeholder={'name,email,quantity\nAma Mensah,ama@example.com,2'} value={csv} disabled={!!preview||issuing} onChange={e=>setCsv(e.target.value)}/></label>{!preview?<button disabled={!csv.trim()} onClick={()=>void review()}>Review guest list</button>:<><div className="suite-table" role="region" tabIndex={0} aria-label="Complimentary pass review"><table><thead><tr><th>Guest</th><th>Email</th><th>Admissions</th><th>Result</th></tr></thead><tbody>{preview.rows.map((x,i)=><tr key={i}><td>{x.name}</td><td>{x.email}</td><td>{x.quantity}</td><td>{results[i]??'Ready to issue'}</td></tr>)}</tbody></table></div><p>{preview.rows.reduce((n,x)=>n+x.quantity,0)} admissions · {Object.keys(results).length} / {preview.rows.length} recipients issued</p><div className="suite-actions"><button disabled={issuing||Object.keys(results).length===preview.rows.length} onClick={()=>void issue()}>{issuing?'Issuing…':Object.keys(results).length?'Resume remaining passes':'Issue reviewed passes'}</button><button disabled={issuing} onClick={()=>{setPreview(null);setResults({});}}>{Object.keys(results).length?'Start another list':'Edit list'}</button></div><p className="suite-note">You can resume after a connection error without issuing duplicates. Each recipient gets private access to their QR passes in My Nights.</p></>}<Message>{m.message}</Message></details></section>;
}
type Question={id:string;prompt:string;kind:string;optionsJson:string|null;required:number;sortOrder:number;status:string;answerCount:number};
export function Questions({event}:{event:string}){
 const r=useRemote<{questions:Question[]}>('questions',event),m=useMutation(),[editing,setEditing]=useState<Question|null>(null),[open,setOpen]=useState(false),[kind,setKind]=useState('text');
 return <section className="suite-section"><header><div><p className="suite-eyebrow">Guest questions</p><h2>Ask before the Night.</h2><p>Questions appear in My Nights for ticket holders. Responses stay attached to the guest.</p></div><button onClick={()=>{setEditing(null);setKind('text');setOpen(true);}}>Add question</button></header><RemoteState error={r.error} loading={!r.data} refresh={r.refresh}/><div className="suite-rows">{r.data?.questions.map(q=><article key={q.id}><div><b>{q.prompt}</b><p>{q.kind==='choice'?'Multiple choice':'Text answer'} · {q.required?'Required':'Optional'} · {q.status} · {q.answerCount} answers</p></div><button onClick={()=>{setEditing(q);setKind(q.kind);setOpen(true);}}>Edit</button></article>)}</div>{open?<form className="suite-detail" key={editing?.id??'new'} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await m.mutate({action:'question_save',eventSlug:event,id:editing?.id,prompt:f.get('prompt'),kind,options:kind==='choice'?String(f.get('options')).split('\n').map(x=>x.trim()).filter(Boolean):[],required:f.get('required')==='on',status:f.get('status'),sortOrder:Number(f.get('sortOrder'))})){setOpen(false);r.refresh();}}}><label>Question<input name="prompt" defaultValue={editing?.prompt} minLength={3} maxLength={300} required/></label><div className="suite-form-grid"><label>Answer type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="text">Text</option><option value="choice">Multiple choice</option></select></label><label>Position<input name="sortOrder" type="number" min={0} max={100} defaultValue={editing?.sortOrder??r.data?.questions.length??0} required/></label><label>Status<select name="status" defaultValue={editing?.status??'active'}><option value="active">Active</option><option value="closed">Closed</option></select></label></div>{kind==='choice'?<label>Options — one per line<textarea name="options" defaultValue={JSON.parse(editing?.optionsJson??'[]').join('\n')} required rows={4}/></label>:null}<label className="suite-check"><input type="checkbox" name="required" defaultChecked={Boolean(editing?.required)}/> Answer required</label>{editing?.answerCount?<p>To preserve existing answers, close this question and add a new one if its wording or options change.</p>:null}<div className="suite-actions"><button disabled={m.busy}>Save question</button><button type="button" disabled={m.busy} onClick={()=>setOpen(false)}>Cancel</button></div></form>:null}<Message>{m.message}</Message></section>;
}
export function Duplicate({event,onCreated}:{event:EventItem;onCreated:(slug:string)=>void}){
 const m=useMutation(),[key,setKey]=useState('');return <details className="suite-disclosure"><summary>Repeat this Night</summary><p>Create a private draft with ticket types and guest questions from this event. Choose a fresh date, review the draft, then submit it to BeCore.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=key||crypto.randomUUID();setKey(id);const d=await m.mutate({action:'duplicate',eventSlug:event.slug,mutationId:id,title:f.get('title'),startsAt:`${f.get('startsAt')}:00.000Z`,endsAt:`${f.get('endsAt')}:00.000Z`});if(d?.eventSlug){setKey('');onCreated(String(d.eventSlug));}}}><label>New event title<input name="title" defaultValue={`${event.title} — next edition`} maxLength={120} minLength={3} required/></label><div className="suite-form-grid"><label>Starts (Accra time)<input name="startsAt" type="datetime-local" required/></label><label>Ends (Accra time)<input name="endsAt" type="datetime-local" required/></label></div><button disabled={m.busy}>Create private draft</button></form><Message>{m.message}</Message></details>;
}
export function Draft({event,onSaved}:{event:string;onSaved:()=>void}){
 const r=useRemote<{draft:{title:string;venue:string;lineup:string;tagline:string|null;startsAt:string;endsAt:string}}>('draft',event),m=useMutation();const d=r.data?.draft;
 return <section className="suite-section"><h2>Make this edition yours.</h2><p>This draft is private. Confirm the details and submit it when it’s ready for BeCore review.</p><RemoteState error={r.error} loading={!d} refresh={r.refresh}/>{d?<form onSubmit={async e=>{e.preventDefault();const native=e.nativeEvent as SubmitEvent,action=(native.submitter as HTMLButtonElement)?.value??'draft_save',f=new FormData(e.currentTarget);if(await m.mutate({action,eventSlug:event,title:f.get('title'),venue:f.get('venue'),lineup:f.get('lineup'),tagline:f.get('tagline'),startsAt:`${f.get('startsAt')}:00.000Z`,endsAt:`${f.get('endsAt')}:00.000Z`,acceptedPolicies:f.get('accepted')==='on'})){r.refresh();onSaved();}}}><div className="suite-form-grid"><label>Title<input name="title" defaultValue={d.title} minLength={3} maxLength={120} required/></label><label>Venue<input name="venue" defaultValue={d.venue} minLength={2} maxLength={160} required/></label><label>Starts (Accra time)<input name="startsAt" type="datetime-local" defaultValue={d.startsAt.slice(0,16)} required/></label><label>Ends (Accra time)<input name="endsAt" type="datetime-local" defaultValue={d.endsAt.slice(0,16)} required/></label></div><label>Line-up<textarea name="lineup" defaultValue={d.lineup} minLength={2} maxLength={1000} required/></label><label>Original event line<input name="tagline" defaultValue={d.tagline??''} maxLength={100}/></label><label className="suite-check"><input name="accepted" type="checkbox"/> I’ve checked the details and accept the <a href="/terms#organizers" target="_blank" rel="noreferrer">host terms</a>.</label><div className="suite-actions"><button value="draft_save" disabled={m.busy}>Save draft</button><button value="draft_submit" disabled={m.busy}>Submit for review</button></div></form>:null}<Message>{m.message}</Message></section>;
}
