'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type {StaffRole} from '../../../lib/staff-roles';
import type {HostApplication} from '../../../lib/host-applications';
import {operationsFetch} from '../../../lib/operations-client';
import OperationsNav from '../operations-nav';
import OrganizerAccess from '../organizer-access';
import './hosts.css';
type Data={items:HostApplication[];counts:{status:string;count:number}[];hosts:{id:string;name:string;slug:string}[]};
const labels:Record<string,string>={pending:'Ready for review',awaiting_email:'Awaiting email',approved:'Approved',rejected:'Declined'};
export default function HostApplications({actor,role,initialApplicationId}:{actor:string;role:StaffRole;initialApplicationId?:string}){
 const [applicationId,setApplicationId]=useState(initialApplicationId);
 const [status,setStatus]=useState('pending'),[page,setPage]=useState(0),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const response=await operationsFetch(`/api/admin/host-applications?status=${status}&page=${page}${applicationId?`&id=${encodeURIComponent(applicationId)}`:''}`,{cache:'no-store',signal:signal??AbortSignal.timeout(15000)});const r=await response.json() as Data & {error?:string};if(!response.ok)throw new Error(r.error??'Could not load applications.');setData(r);if(applicationId&&r.items[0])setStatus(r.items[0].status);setError('');}catch(cause){if(!signal?.aborted)setError(cause instanceof Error?cause.message:'Could not load applications.');}finally{if(!signal?.aborted)setLoading(false);}},[status,page,applicationId]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 async function review(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();if(busy)return;const form=new FormData(event.currentTarget),action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'approve';setBusy(id);setError('');setNotice('');try{const response=await operationsFetch('/api/admin/host-applications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action,note:form.get('note'),hostId:form.get('hostId')||undefined}),signal:AbortSignal.timeout(20000)});const r=await response.json() as {error?:string};if(!response.ok)throw new Error(r.error??'The decision could not be saved.');setNotice(action==='approve'?'Host approved. Account access is being prepared; check Approved for delivery status.':'Application declined. The outcome email is queued.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Could not confirm the decision. Refresh before trying again.');}finally{setBusy('');}}
 const count=data?.counts.find(x=>x.status===status)?.count??0;
 return <main className="admin-dashboard"><OperationsNav actor={actor} role={role} active="/admin/hosts"/><section className="host-applications"><header><div><p>Hosts</p><h1>Host applications</h1><p>Review the person or brand before granting verified host access.</p></div><button onClick={()=>void load()} disabled={loading}>Refresh</button></header><nav aria-label="Application status">{Object.entries(labels).map(([key,label])=><button key={key} aria-pressed={status===key} disabled={Boolean(busy)} onClick={()=>{setApplicationId(undefined);setStatus(key);setPage(0);setData(null);}}>{label} <span>{data?.counts.find(x=>x.status===key)?.count??0}</span></button>)}</nav>{notice?<p role="status">{notice}</p>:null}{error?<p role="alert">{error}</p>:null}{loading?<p role="status">Loading applications…</p>:null}{!loading&&data?.items.length===0?<p>{applicationId?'This application is no longer available. Choose a queue above.':'No applications in this queue.'}</p>:null}
 {data?.items.map(item=><details key={item.id} open={applicationId===item.id?true:undefined}><summary><span><b>{item.brandName}</b><small>{item.contactName}</small></span><span>{new Date(item.createdAt).toLocaleDateString('en-GB')} · {labels[item.status]}</span></summary><div className="host-applications__details"><dl><div><dt>Email</dt><dd>{item.email}</dd></div><div><dt>Phone / WhatsApp</dt><dd>{item.phone}</dd></div><div><dt>Social / website</dt><dd><a href={item.socialUrl} target="_blank" rel="noopener noreferrer">{item.socialUrl}</a></dd></div></dl>{item.about?<p>{item.about}</p>:null}{item.reviewNote?<p>Review note: {item.reviewNote}</p>:null}{item.status==='pending'?<form onSubmit={event=>void review(event,item.id)}><label>Public host profile<select name="hostId" defaultValue=""><option value="">Create a new profile for {item.brandName}</option>{data.hosts.map(host=><option key={host.id} value={host.id}>Use existing: {host.name} ({host.slug})</option>)}</select></label><label>Internal review note <span>optional</span><textarea name="note" maxLength={600}/></label><div className="host-applications__actions"><button type="submit" value="approve" disabled={Boolean(busy)}>{busy===item.id?'Saving…':'Approve host'}</button><button type="submit" value="reject" disabled={Boolean(busy)}>Decline</button></div></form>:null}{item.status==='awaiting_email'?<p>The applicant must confirm their email before approval.</p>:null}{item.accountId?<><OrganizerAccess accountId={item.accountId}/><Link href="/admin/accounts">Manage account access</Link></>:null}</div></details>)}
 {!applicationId&&count>20?<footer><button disabled={page===0||loading} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.ceil(count/20)}</span><button disabled={(page+1)*20>=count||loading} onClick={()=>setPage(page+1)}>Next</button></footer>:null}</section></main>;
}
